// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5) }

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0x83, 0x46, 0x89, 0x85, 0xd5, 0x58, 0x13, 0x34, 0x8b, 0x17, 0xf7, 0xa4, 0x24, 0xee,
	0x46, 0xf0, 0x84, 0x37, 0xd4, 0x18, 0x0e, 0x4a, 0x82, 0xd1, 0x83, 0xb7, 0xb2, 0x3b, 0xe2, 0xaa,
	0xb4, 0xb5, 0x2d, 0x24, 0xc4, 0x70, 0xf1, 0x15, 0x7c, 0x24, 0x1f, 0xc1, 0x57, 0xf0, 0x41, 0x4c,
	0x3b, 0x75, 0x03, 0x9c, 0x3c, 0x4d, 0xbe, 0xce, 0xcc, 0xf7, 0x4f, 0x76, 0x49, 0x30, 0x60, 0xe9,
	0x0b, 0xf0, 0x2c, 0x96, 0x4a, 0x18, 0x41, 0xd7, 0x5c, 0x09, 0xeb, 0x43, 0x21, 0x86, 0xaf, 0x90,
	0x38, 0x1a, 0x8c, 0x1f, 0x13, 0x18, 0x49, 0x33, 0xc5, 0x99, 0x70, 0xdf, 0x37, 0x99, 0xcc, 0x13,
	0xc6, 0xb9, 0x30, 0xcc, 0xe4, 0x82, 0x6b, 0xdf, 0xad, 0xea, 0xf4, 0x09, 0x46, 0x0c, 0xa9, 0xf9,
	0xb5, 0x4a, 0xca, 0x1d, 0x4c, 0xa0, 0x37, 0xa4, 0x7c, 0x0f, 0x4a, 0xe7, 0x82, 0xd3, 0x5a, 0x8c,
	0x8e, 0xf8, 0x2f, 0x20, 0xbe, 0xb4, 0x01, 0x61, 0x0d, 0x1f, 0x62, 0x3f, 0xd7, 0x07, 0x2d, 0x05,
	0xd7, 0x10, 0xed, 0x7c, 0x7c, 0xff, 0x7c, 0xae, 0x04, 0xb4, 0x92, 0x4c, 0x4e, 0x92, 0x89, 0x97,
	0xf4, 0x48, 0xf5, 0x5c, 0x01, 0x33, 0x70, 0xeb, 0x12, 0x69, 0xe0, 0x97, 0x11, 0xc3, 0x45, 0x8c,
	0x0e, 0x9c, 0xa2, 0x1e, 0xd5, 0xac, 0x02, 0x6f, 0x4c, 0xde, 0xa5, 0x12, 0xcf, 0x90, 0x9a, 0xee,
	0xc5, 0xac, 0x5d, 0x6a, 0xd0, 0x6b, 0xb2, 0x71, 0x05, 0xc6, 0xdb, 0xf6, 0xfc, 0x7a, 0x1f, 0xde,
	0xc6, 0xa0, 0x4d, 0x6f, 0x60, 0x07, 0x3b, 0xd3, 0x6e, 0xb6, 0x2c, 0xde, 0x75, 0xe2, 0x6d, 0xba,
	0x35, 0x2f, 0xce, 0xb3, 0x19, 0x05, 0x12, 0xe0, 0x7d, 0x7d, 0x48, 0x85, 0xca, 0x34, 0xdd, 0x2c,
	0x94, 0x8e, 0xc3, 0x25, 0x8e, 0x4e, 0x9d, 0x29, 0x8e, 0x8e, 0xac, 0x69, 0xee, 0xb6, 0xc2, 0x8a,
	0xd5, 0xbe, 0x28, 0x5c, 0xb1, 0x57, 0x33, 0x52, 0xbd, 0x93, 0x59, 0x11, 0x53, 0x7c, 0x06, 0xc4,
	0x70, 0x11, 0xa3, 0x96, 0xcb, 0x38, 0x6e, 0x1e, 0xfe, 0x37, 0xa3, 0x5d, 0x6a, 0x74, 0x82, 0x87,
	0x8a, 0x93, 0x9c, 0xe1, 0xef, 0x5a, 0x77, 0xa5, 0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xa1,
	0x67, 0xa9, 0x3c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendClient interface {
	// Version
	Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	// Create Schema
	CreateSchema(ctx context.Context, in *Schema, opts ...grpc.CallOption) (*Schema, error)
	// Get Schema
	GetSchema(ctx context.Context, in *RequestObjectById, opts ...grpc.CallOption) (*Schema, error)
	// CreateRecords
	CreateRecords(ctx context.Context, in *Records, opts ...grpc.CallOption) (*Records, error)
	// UpdateRecord
	UpdateRecord(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Record, error)
}

type backendClient struct {
	cc *grpc.ClientConn
}

func NewBackendClient(cc *grpc.ClientConn) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) Version(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/proto.Backend/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CreateSchema(ctx context.Context, in *Schema, opts ...grpc.CallOption) (*Schema, error) {
	out := new(Schema)
	err := c.cc.Invoke(ctx, "/proto.Backend/CreateSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetSchema(ctx context.Context, in *RequestObjectById, opts ...grpc.CallOption) (*Schema, error) {
	out := new(Schema)
	err := c.cc.Invoke(ctx, "/proto.Backend/GetSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) CreateRecords(ctx context.Context, in *Records, opts ...grpc.CallOption) (*Records, error) {
	out := new(Records)
	err := c.cc.Invoke(ctx, "/proto.Backend/CreateRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UpdateRecord(ctx context.Context, in *Record, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/proto.Backend/UpdateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
type BackendServer interface {
	// Version
	Version(context.Context, *empty.Empty) (*VersionResponse, error)
	// Create Schema
	CreateSchema(context.Context, *Schema) (*Schema, error)
	// Get Schema
	GetSchema(context.Context, *RequestObjectById) (*Schema, error)
	// CreateRecords
	CreateRecords(context.Context, *Records) (*Records, error)
	// UpdateRecord
	UpdateRecord(context.Context, *Record) (*Record, error)
}

// UnimplementedBackendServer can be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (*UnimplementedBackendServer) Version(ctx context.Context, req *empty.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedBackendServer) CreateSchema(ctx context.Context, req *Schema) (*Schema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchema not implemented")
}
func (*UnimplementedBackendServer) GetSchema(ctx context.Context, req *RequestObjectById) (*Schema, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (*UnimplementedBackendServer) CreateRecords(ctx context.Context, req *Records) (*Records, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecords not implemented")
}
func (*UnimplementedBackendServer) UpdateRecord(ctx context.Context, req *Record) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecord not implemented")
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backend/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Version(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CreateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Schema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CreateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backend/CreateSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CreateSchema(ctx, req.(*Schema))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestObjectById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backend/GetSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetSchema(ctx, req.(*RequestObjectById))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_CreateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Records)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).CreateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backend/CreateRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).CreateRecords(ctx, req.(*Records))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Backend/UpdateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UpdateRecord(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Backend_Version_Handler,
		},
		{
			MethodName: "CreateSchema",
			Handler:    _Backend_CreateSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _Backend_GetSchema_Handler,
		},
		{
			MethodName: "CreateRecords",
			Handler:    _Backend_CreateRecords_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _Backend_UpdateRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
