// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestObjectById struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestObjectById) Reset()         { *m = RequestObjectById{} }
func (m *RequestObjectById) String() string { return proto.CompactTextString(m) }
func (*RequestObjectById) ProtoMessage()    {}
func (*RequestObjectById) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *RequestObjectById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestObjectById.Unmarshal(m, b)
}
func (m *RequestObjectById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestObjectById.Marshal(b, m, deterministic)
}
func (m *RequestObjectById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestObjectById.Merge(m, src)
}
func (m *RequestObjectById) XXX_Size() int {
	return xxx_messageInfo_RequestObjectById.Size(m)
}
func (m *RequestObjectById) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestObjectById.DiscardUnknown(m)
}

var xxx_messageInfo_RequestObjectById proto.InternalMessageInfo

func (m *RequestObjectById) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Column struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	MinLength            int32    `protobuf:"varint,2,opt,name=minLength,proto3" json:"minLength,omitempty"`
	MaxLength            int32    `protobuf:"varint,3,opt,name=maxLength,proto3" json:"maxLength,omitempty"`
	Minimum              int64    `protobuf:"varint,4,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              int64    `protobuf:"varint,5,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Column) GetMinLength() int32 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *Column) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *Column) GetMinimum() int64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *Column) GetMaximum() int64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type Schema struct {
	Type                 string             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string             `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Properties           map[string]*Column `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Required             []string           `protobuf:"bytes,4,rep,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Schema) GetProperties() map[string]*Column {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "proto.VersionResponse")
	proto.RegisterType((*RequestObjectById)(nil), "proto.RequestObjectById")
	proto.RegisterType((*Column)(nil), "proto.Column")
	proto.RegisterType((*Schema)(nil), "proto.Schema")
	proto.RegisterMapType((map[string]*Column)(nil), "proto.Schema.PropertiesEntry")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xa4, 0x29, 0xf4, 0x4a, 0x29, 0x58, 0x0c, 0x51, 0x05, 0x52, 0x94, 0x0e, 0x64,
	0xca, 0x50, 0x16, 0x04, 0x62, 0x29, 0x62, 0x40, 0xaa, 0x04, 0x32, 0x12, 0x03, 0x5b, 0xda, 0x9c,
	0xa8, 0xa1, 0x71, 0x52, 0xdb, 0x41, 0xcd, 0x3b, 0xf0, 0x7a, 0xbc, 0x0f, 0xaa, 0xed, 0x14, 0x84,
	0x58, 0x72, 0xf7, 0xdf, 0x97, 0x3b, 0xff, 0x3e, 0xc3, 0x81, 0x5a, 0x2c, 0xb1, 0xc8, 0xd2, 0x4a,
	0x96, 0xba, 0xa4, 0x81, 0x09, 0xf1, 0x39, 0x0c, 0x9f, 0x51, 0x2a, 0x5e, 0x0a, 0x86, 0xaa, 0x2a,
	0x85, 0x42, 0x7a, 0x02, 0xc1, 0x47, 0xb6, 0xaa, 0x31, 0x24, 0x11, 0x49, 0x7a, 0xcc, 0x8a, 0x78,
	0x0c, 0xc7, 0x0c, 0xd7, 0x35, 0x2a, 0xfd, 0x30, 0x7f, 0xc3, 0x85, 0x9e, 0x36, 0xf7, 0x39, 0x3d,
	0x04, 0x8f, 0xe7, 0xee, 0x3f, 0x8f, 0xe7, 0xf1, 0x27, 0x81, 0xee, 0x6d, 0xb9, 0xaa, 0x0b, 0x41,
	0x29, 0x74, 0x74, 0x53, 0xb5, 0x43, 0x4c, 0x4e, 0x4f, 0xa1, 0x57, 0x70, 0x31, 0x43, 0xf1, 0xaa,
	0x97, 0xa1, 0x17, 0x91, 0x24, 0x60, 0x3f, 0x05, 0x43, 0xb3, 0x8d, 0xa3, 0xbe, 0xa3, 0x6d, 0x81,
	0x86, 0xb0, 0x57, 0x70, 0xc1, 0x8b, 0xba, 0x08, 0x3b, 0x11, 0x49, 0x7c, 0xd6, 0x4a, 0x43, 0xb2,
	0x8d, 0x21, 0x81, 0x23, 0x56, 0xc6, 0x5f, 0x04, 0xba, 0x4f, 0xe6, 0xd2, 0xff, 0xda, 0xb1, 0xee,
	0xbd, 0xd6, 0x3d, 0xbd, 0x01, 0xa8, 0x64, 0x59, 0xa1, 0xd4, 0x1c, 0x55, 0xe8, 0x47, 0x7e, 0xd2,
	0x9f, 0x9c, 0xd9, 0x75, 0xa5, 0x76, 0x4c, 0xfa, 0xb8, 0xe3, 0x77, 0x42, 0xcb, 0x86, 0xfd, 0x6a,
	0xa0, 0x23, 0xd8, 0x97, 0xb8, 0xae, 0xb9, 0xc4, 0x3c, 0xec, 0x44, 0x7e, 0xd2, 0x63, 0x3b, 0x3d,
	0x9a, 0xc1, 0xf0, 0x4f, 0x2b, 0x3d, 0x02, 0xff, 0x1d, 0x1b, 0x67, 0x68, 0x9b, 0xd2, 0x71, 0xbb,
	0xf8, 0xad, 0xa5, 0xfe, 0x64, 0xe0, 0x8e, 0xb6, 0x0b, 0x75, 0xef, 0x70, 0xe5, 0x5d, 0x92, 0xe9,
	0xe0, 0xa5, 0x6f, 0xd0, 0xb5, 0xf9, 0xce, 0xbb, 0x26, 0x5c, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0xce, 0x74, 0x3c, 0xe1, 0x01, 0x00, 0x00,
}
