// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VersionResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestObjectById struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestObjectById) Reset()         { *m = RequestObjectById{} }
func (m *RequestObjectById) String() string { return proto.CompactTextString(m) }
func (*RequestObjectById) ProtoMessage()    {}
func (*RequestObjectById) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *RequestObjectById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestObjectById.Unmarshal(m, b)
}
func (m *RequestObjectById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestObjectById.Marshal(b, m, deterministic)
}
func (m *RequestObjectById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestObjectById.Merge(m, src)
}
func (m *RequestObjectById) XXX_Size() int {
	return xxx_messageInfo_RequestObjectById.Size(m)
}
func (m *RequestObjectById) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestObjectById.DiscardUnknown(m)
}

var xxx_messageInfo_RequestObjectById proto.InternalMessageInfo

func (m *RequestObjectById) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Column struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	MinLength            int32    `protobuf:"varint,2,opt,name=minLength,proto3" json:"minLength,omitempty"`
	MaxLength            int32    `protobuf:"varint,3,opt,name=maxLength,proto3" json:"maxLength,omitempty"`
	Minimum              int64    `protobuf:"varint,4,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              int64    `protobuf:"varint,5,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Default              *any.Any `protobuf:"bytes,6,opt,name=default,proto3" json:"default,omitempty"`
	Enum                 *any.Any `protobuf:"bytes,7,opt,name=enum,proto3" json:"enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Column) GetMinLength() int32 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *Column) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *Column) GetMinimum() int64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *Column) GetMaximum() int64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *Column) GetDefault() *any.Any {
	if m != nil {
		return m.Default
	}
	return nil
}

func (m *Column) GetEnum() *any.Any {
	if m != nil {
		return m.Enum
	}
	return nil
}

type StringType struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MinLength            int32    `protobuf:"varint,3,opt,name=minLength,proto3" json:"minLength,omitempty"`
	MaxLength            int32    `protobuf:"varint,4,opt,name=maxLength,proto3" json:"maxLength,omitempty"`
	Default              string   `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringType) Reset()         { *m = StringType{} }
func (m *StringType) String() string { return proto.CompactTextString(m) }
func (*StringType) ProtoMessage()    {}
func (*StringType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *StringType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringType.Unmarshal(m, b)
}
func (m *StringType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringType.Marshal(b, m, deterministic)
}
func (m *StringType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringType.Merge(m, src)
}
func (m *StringType) XXX_Size() int {
	return xxx_messageInfo_StringType.Size(m)
}
func (m *StringType) XXX_DiscardUnknown() {
	xxx_messageInfo_StringType.DiscardUnknown(m)
}

var xxx_messageInfo_StringType proto.InternalMessageInfo

func (m *StringType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StringType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StringType) GetMinLength() int32 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *StringType) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *StringType) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

type IntegerType struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Minimum              int64    `protobuf:"varint,3,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              int64    `protobuf:"varint,4,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Default              int64    `protobuf:"varint,5,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntegerType) Reset()         { *m = IntegerType{} }
func (m *IntegerType) String() string { return proto.CompactTextString(m) }
func (*IntegerType) ProtoMessage()    {}
func (*IntegerType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *IntegerType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegerType.Unmarshal(m, b)
}
func (m *IntegerType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegerType.Marshal(b, m, deterministic)
}
func (m *IntegerType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegerType.Merge(m, src)
}
func (m *IntegerType) XXX_Size() int {
	return xxx_messageInfo_IntegerType.Size(m)
}
func (m *IntegerType) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegerType.DiscardUnknown(m)
}

var xxx_messageInfo_IntegerType proto.InternalMessageInfo

func (m *IntegerType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IntegerType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *IntegerType) GetMinimum() int64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *IntegerType) GetMaximum() int64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *IntegerType) GetDefault() int64 {
	if m != nil {
		return m.Default
	}
	return 0
}

type FloatType struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Minimum              float64  `protobuf:"fixed64,3,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Maximum              float64  `protobuf:"fixed64,4,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Default              float64  `protobuf:"fixed64,5,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FloatType) Reset()         { *m = FloatType{} }
func (m *FloatType) String() string { return proto.CompactTextString(m) }
func (*FloatType) ProtoMessage()    {}
func (*FloatType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *FloatType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatType.Unmarshal(m, b)
}
func (m *FloatType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatType.Marshal(b, m, deterministic)
}
func (m *FloatType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatType.Merge(m, src)
}
func (m *FloatType) XXX_Size() int {
	return xxx_messageInfo_FloatType.Size(m)
}
func (m *FloatType) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatType.DiscardUnknown(m)
}

var xxx_messageInfo_FloatType proto.InternalMessageInfo

func (m *FloatType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FloatType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FloatType) GetMinimum() float64 {
	if m != nil {
		return m.Minimum
	}
	return 0
}

func (m *FloatType) GetMaximum() float64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func (m *FloatType) GetDefault() float64 {
	if m != nil {
		return m.Default
	}
	return 0
}

type DateTimeType struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Default              string   `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	Format               string   `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateTimeType) Reset()         { *m = DateTimeType{} }
func (m *DateTimeType) String() string { return proto.CompactTextString(m) }
func (*DateTimeType) ProtoMessage()    {}
func (*DateTimeType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *DateTimeType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateTimeType.Unmarshal(m, b)
}
func (m *DateTimeType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateTimeType.Marshal(b, m, deterministic)
}
func (m *DateTimeType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateTimeType.Merge(m, src)
}
func (m *DateTimeType) XXX_Size() int {
	return xxx_messageInfo_DateTimeType.Size(m)
}
func (m *DateTimeType) XXX_DiscardUnknown() {
	xxx_messageInfo_DateTimeType.DiscardUnknown(m)
}

var xxx_messageInfo_DateTimeType proto.InternalMessageInfo

func (m *DateTimeType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DateTimeType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DateTimeType) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *DateTimeType) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type BooleanType struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooleanType) Reset()         { *m = BooleanType{} }
func (m *BooleanType) String() string { return proto.CompactTextString(m) }
func (*BooleanType) ProtoMessage()    {}
func (*BooleanType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *BooleanType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooleanType.Unmarshal(m, b)
}
func (m *BooleanType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooleanType.Marshal(b, m, deterministic)
}
func (m *BooleanType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooleanType.Merge(m, src)
}
func (m *BooleanType) XXX_Size() int {
	return xxx_messageInfo_BooleanType.Size(m)
}
func (m *BooleanType) XXX_DiscardUnknown() {
	xxx_messageInfo_BooleanType.DiscardUnknown(m)
}

var xxx_messageInfo_BooleanType proto.InternalMessageInfo

func (m *BooleanType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BooleanType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Schema struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Properties           map[string]*_struct.Struct `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Required             []string                   `protobuf:"bytes,3,rep,name=required,proto3" json:"required,omitempty"`
	Name                 string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ProjectID            string                     `protobuf:"bytes,5,opt,name=projectID,proto3" json:"projectID,omitempty"`
	Version              string                     `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Schema) Reset()         { *m = Schema{} }
func (m *Schema) String() string { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()    {}
func (*Schema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}

func (m *Schema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schema.Unmarshal(m, b)
}
func (m *Schema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schema.Marshal(b, m, deterministic)
}
func (m *Schema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schema.Merge(m, src)
}
func (m *Schema) XXX_Size() int {
	return xxx_messageInfo_Schema.Size(m)
}
func (m *Schema) XXX_DiscardUnknown() {
	xxx_messageInfo_Schema.DiscardUnknown(m)
}

var xxx_messageInfo_Schema proto.InternalMessageInfo

func (m *Schema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Schema) GetProperties() map[string]*_struct.Struct {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Schema) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Schema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Schema) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *Schema) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "proto.VersionResponse")
	proto.RegisterType((*RequestObjectById)(nil), "proto.RequestObjectById")
	proto.RegisterType((*Column)(nil), "proto.Column")
	proto.RegisterType((*StringType)(nil), "proto.StringType")
	proto.RegisterType((*IntegerType)(nil), "proto.IntegerType")
	proto.RegisterType((*FloatType)(nil), "proto.FloatType")
	proto.RegisterType((*DateTimeType)(nil), "proto.DateTimeType")
	proto.RegisterType((*BooleanType)(nil), "proto.BooleanType")
	proto.RegisterType((*Schema)(nil), "proto.Schema")
	proto.RegisterMapType((map[string]*_struct.Struct)(nil), "proto.Schema.PropertiesEntry")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xd5, 0xda, 0x49, 0xfa, 0x79, 0xdc, 0x8f, 0xc2, 0xaa, 0x02, 0x13, 0x15, 0xc9, 0x32, 0x07,
	0x7c, 0xc1, 0x95, 0xca, 0x05, 0x81, 0x38, 0x90, 0x16, 0xa4, 0x48, 0x48, 0x20, 0xa7, 0xea, 0x81,
	0xdb, 0x36, 0x9e, 0xa4, 0x0b, 0xf6, 0xae, 0xbb, 0x5e, 0x47, 0xf5, 0xaf, 0x40, 0x9c, 0xe0, 0x17,
	0xf2, 0x3b, 0x90, 0xd7, 0x76, 0x93, 0x86, 0xa4, 0x07, 0xca, 0x69, 0xf7, 0xcd, 0x9b, 0x5d, 0xbf,
	0x79, 0xde, 0x19, 0xd8, 0x2d, 0xa6, 0x17, 0x98, 0xb1, 0x28, 0x57, 0x52, 0x4b, 0xda, 0x37, 0xcb,
	0xf0, 0x60, 0x2e, 0xe5, 0x3c, 0xc5, 0x43, 0x83, 0xce, 0xcb, 0xd9, 0x61, 0xa1, 0x55, 0x39, 0xd5,
	0x4d, 0xd2, 0xf0, 0xf1, 0x3a, 0xcb, 0x44, 0xd5, 0x50, 0xc1, 0x33, 0xd8, 0x3b, 0x43, 0x55, 0x70,
	0x29, 0x62, 0x2c, 0x72, 0x29, 0x0a, 0xa4, 0xfb, 0xd0, 0x5f, 0xb0, 0xb4, 0x44, 0x8f, 0xf8, 0x24,
	0x74, 0xe2, 0x06, 0x04, 0x4f, 0xe1, 0x41, 0x8c, 0x97, 0x25, 0x16, 0xfa, 0xe3, 0xf9, 0x17, 0x9c,
	0xea, 0x51, 0x35, 0x4e, 0xe8, 0x3d, 0xb0, 0x78, 0xd2, 0xe6, 0x59, 0x3c, 0x09, 0x7e, 0x11, 0x18,
	0x1c, 0xcb, 0xb4, 0xcc, 0x04, 0xa5, 0xd0, 0xd3, 0x55, 0xde, 0x5d, 0x62, 0xf6, 0xf4, 0x00, 0x9c,
	0x8c, 0x8b, 0x0f, 0x28, 0xe6, 0xfa, 0xc2, 0xb3, 0x7c, 0x12, 0xf6, 0xe3, 0x65, 0xc0, 0xb0, 0xec,
	0xaa, 0x65, 0xed, 0x96, 0xed, 0x02, 0xd4, 0x83, 0x9d, 0x8c, 0x0b, 0x9e, 0x95, 0x99, 0xd7, 0xf3,
	0x49, 0x68, 0xc7, 0x1d, 0x34, 0x0c, 0xbb, 0x32, 0x4c, 0xbf, 0x65, 0x1a, 0x48, 0x23, 0xd8, 0x49,
	0x70, 0xc6, 0xca, 0x54, 0x7b, 0x03, 0x9f, 0x84, 0xee, 0xd1, 0x7e, 0xd4, 0x38, 0x11, 0x75, 0x4e,
	0x44, 0x6f, 0x45, 0x15, 0x77, 0x49, 0x34, 0x84, 0x1e, 0x8a, 0x32, 0xf3, 0x76, 0x6e, 0x49, 0x36,
	0x19, 0xc1, 0x4f, 0x02, 0x30, 0xd1, 0x8a, 0x8b, 0xf9, 0x69, 0x5d, 0xd8, 0xa6, 0x62, 0x7d, 0x70,
	0x13, 0x2c, 0xa6, 0x8a, 0xe7, 0x9a, 0x4b, 0x61, 0xca, 0x75, 0xe2, 0xd5, 0xd0, 0x4d, 0x3b, 0xec,
	0x5b, 0xed, 0xe8, 0x6d, 0xb0, 0xa3, 0x2b, 0xad, 0x6f, 0x6e, 0xee, 0x60, 0xf0, 0x9d, 0x80, 0x3b,
	0x16, 0x1a, 0xe7, 0xa8, 0xee, 0xa0, 0x6d, 0xc5, 0x6e, 0x7b, 0xab, 0xdd, 0xbd, 0x9b, 0x76, 0xaf,
	0x69, 0xb2, 0x97, 0x9a, 0xbe, 0x11, 0x70, 0xde, 0xa7, 0x92, 0xe9, 0x7f, 0xa7, 0x88, 0x6c, 0x55,
	0x44, 0xb6, 0x2a, 0x22, 0x4b, 0x45, 0x0b, 0xd8, 0x3d, 0x61, 0x1a, 0x4f, 0x79, 0x86, 0x77, 0xd3,
	0xb4, 0xf9, 0x2f, 0xd0, 0x87, 0x30, 0x98, 0x49, 0x95, 0xb1, 0xe6, 0xe5, 0x39, 0x71, 0x8b, 0x82,
	0x63, 0x70, 0x47, 0x52, 0xa6, 0xc8, 0xc4, 0xdf, 0x7f, 0x36, 0xf8, 0x61, 0xc1, 0x60, 0x62, 0xa6,
	0xc0, 0x7a, 0x07, 0xd2, 0x37, 0x00, 0xb9, 0x92, 0x39, 0x2a, 0xcd, 0xb1, 0xf0, 0x2c, 0xdf, 0x0e,
	0xdd, 0xa3, 0x27, 0xcd, 0x0b, 0x8e, 0x9a, 0x23, 0xd1, 0xa7, 0x6b, 0xfe, 0x9d, 0xd0, 0xaa, 0x8a,
	0x57, 0x0e, 0xd0, 0x21, 0xfc, 0xa7, 0xf0, 0xb2, 0xe4, 0x0a, 0x13, 0xcf, 0xf6, 0xed, 0xd0, 0x89,
	0xaf, 0x71, 0xad, 0x55, 0xb0, 0x0c, 0x8d, 0xc7, 0x4e, 0x6c, 0xf6, 0xf5, 0x23, 0xcd, 0x95, 0xac,
	0xe7, 0xc1, 0xf8, 0xa4, 0xb5, 0x60, 0x19, 0xa8, 0xed, 0x59, 0x34, 0xc3, 0xa5, 0x75, 0xa1, 0x83,
	0xc3, 0x33, 0xd8, 0x5b, 0x93, 0x41, 0xef, 0x83, 0xfd, 0x15, 0xab, 0xb6, 0x94, 0x7a, 0x4b, 0x9f,
	0x77, 0x83, 0xc8, 0x32, 0xfd, 0xf8, 0xe8, 0x8f, 0x7e, 0x9c, 0x98, 0x21, 0xd7, 0x4e, 0xa8, 0x57,
	0xd6, 0x4b, 0x32, 0xfa, 0xff, 0xb3, 0x6b, 0xd8, 0xd7, 0x4d, 0xce, 0xc0, 0x2c, 0x2f, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x48, 0xf9, 0xf6, 0x25, 0x34, 0x05, 0x00, 0x00,
}
